# Server settings
server:
  port: 9002

# Spring
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# Search Engine

# Lucene
lucene:
  dataFile: g14-app-answering-user-ranking/src/main/resources/Posts_10000.xml
  indexPath: target/app-answering-user-ranking/index
  rankingFile: target/app-answering-user-ranking/index/ranking.data
  willIndex: false
  maxUserCount: 200
