# Server
server:
  port: 9000

# Spring
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# Lucene
lucene:
  dataFile: /Users/jackjones/Workspaces/IR/resources/Posts.xml
  indexPath: target/search-engine/index
  willIndex: false
  indexTags: java, c, c++, python
